/* ============================================================
   extract.js — slice the generator cores out of the authoring
   tools and emit standalone game modules.

   The tools stay single-file (that's right for a tool). The game
   needs the generators without their UI, and needs both loaded
   side by side — they both declare `clamp` at top level, so each
   core is wrapped in an IIFE and published under one global.

   No build step is required to *play*: src/gen/*.js is committed.
   Re-run this only after editing a tool:

       node tools/extract.js
   ============================================================ */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* Pull the one <script> body out of a single-file tool. */
function scriptBody(html) {
  const a = html.indexOf('<script>');
  const b = html.lastIndexOf('</script>');
  if (a < 0 || b < 0) throw new Error('no <script> block');
  return html.slice(a + '<script>'.length, b);
}

/* Wrap a core in an IIFE so the two generators cannot collide. */
function wrap(banner, global, core, exports) {
  return `/* ============================================================
   ${banner}

   GENERATED by tools/extract.js — do not edit by hand.
   Edit the tool it came from, then re-run the extractor.
   ============================================================ */
window.${global} = (function () {
"use strict";
${core.trim()}

return { ${exports.join(', ')} };
})();
`;
}

/* ---------------- greebleworks ---------------- */
function greebleworks() {
  const js = scriptBody(read('tools/greebleworks.html'));
  // The UI section is the last banner; everything above it is generator.
  const uiAt = js.indexOf('   UI\n');
  if (uiAt < 0) throw new Error('greebleworks: UI banner not found');
  let core = js.slice(0, js.lastIndexOf('/* =', uiAt));
  core = core.replace(/^\s*"use strict";\s*/, '');

  // The compositor draws 7 layers; the game needs to put entities
  // between the play layer and the foreground. One optional hook.
  const hookAt = core.indexOf('  // lamps and signs');
  if (hookAt < 0) throw new Error('greebleworks: entity hook site not found');
  core = core.slice(0, hookAt)
       + '  if (entityPass) entityPass(ctx, scroll, time);\n\n'
       + core.slice(hookAt);
  core = core.replace(
    'function drawLevelFrame(L,cfg,ctx,scroll,time){',
    'function drawLevelFrame(L,cfg,ctx,scroll,time,entityPass){');

  return wrap('GREEBLEWORKS — generator core (UI stripped)', 'GREEBLEWORKS', core, [
    'LV', 'PALETTES', 'PAL_RGB', 'STYLES', 'SKYMOODS', 'CITY_PRESETS',
    'DECAL_KINDS', 'DECAL_CATS', 'WIRE_STYLE',
    'buildLevel', 'drawLevelFrame', 'bakeFacade', 'bakePlatform', 'bakeRoof',
    'bakeDecal', 'bakeSky', 'makeRng', 'clamp', 'hex2rgb', 'rgbStr', 'mkCanvas'
  ]);
}

/* ---------------- merc forge ---------------- */
function mercforge() {
  const js = scriptBody(read('tools/mercforge.html'));
  const uiAt = js.indexOf('/* ---------- UI ----------');
  if (uiAt < 0) throw new Error('mercforge: UI banner not found');
  const core = js.slice(0, uiAt);

  /* buildSheet() reads the module-global P. The game needs sheets for
     the player and several enemy archetypes, so expose a pure entry
     point that swaps P for the duration of one synchronous build. */
  const shim = `
/* ---------- game entry point ---------- */
const P_DEFAULTS = Object.assign({}, P);

/* randomParams() is not shimmed here: it lives in the tool core, which
   is the whole point — a copy of it in this file drifted from the tool
   the first time the proportions were retuned.

   Build a sheet from an explicit param set. Synchronous, so swapping
   the module-global P around the call is safe. */
function forge(params) {
  const saved = Object.assign({}, P);
  Object.assign(P, P_DEFAULTS, params || {});
  try { return buildSheet(); }
  finally { Object.assign(P, saved); }
}

`;

  return wrap('MERC FORGE — generator core (UI + demo stripped)', 'MERCFORGE', core + shim, [
    'P_DEFAULTS', 'CONTROLS', 'PRESETS', 'forge', 'randomParams',
    'states', 'gunSpec', 'buildPalette', 'hsl', 'shade', 'hx', 'rh', 'rng', 'clamp'
  ]);
}

/* ---------------- crawler forge ---------------- */
function crawlerforge() {
  const js = scriptBody(read('tools/crawlerforge.html'));
  const uiAt = js.indexOf('   UI\n');
  if (uiAt < 0) throw new Error('crawlerforge: UI banner not found');
  let core = js.slice(0, js.lastIndexOf('/* =', uiAt));
  core = core.replace(/^\s*"use strict";\s*/, '');

  /* drawTentacle sits above the UI banner in the tool — it is runtime
     code, and the game and the tool's own preview share it — so the
     core slice already carries it. */
  if (core.indexOf('function drawTentacle(') < 0)
    throw new Error('crawlerforge: drawTentacle fell outside the core slice');

  /* Same shape as MERC FORGE's forge(): buildSheet() reads the module
     global P, so give the game a pure entry point that swaps it for
     the duration of one synchronous build. */
  const shim = `
/* ---------- game entry point ---------- */
const P_DEFAULTS = Object.assign({}, P);

function forge(params) {
  const saved = Object.assign({}, P);
  Object.assign(P, P_DEFAULTS, params || {});
  try { return buildSheet(); }
  finally { Object.assign(P, saved); }
}

/* The tool's randomizer as a pure function of a seed. */
function randomParams(seed) {
  const R = makeRng(seed >>> 0);
  return {
    seed: seed >>> 0,
    size: R.int(22, 44),
    lobes: R.int(3, 9),
    chaos: R.range(0.25, 1.05),
    squat: R.range(0.7, 1.35),
    asym: R.range(0.15, 1.1),
    metal: R.range(0.05, 0.85),
    plates: R.range(0.2, 1.6),
    bolts: R.range(0.3, 1.6),
    rebar: R.range(0, 1.4),
    spikes: R.range(0, 1.5),
    veins: R.range(0.3, 1.6),
    pustules: R.range(0.2, 1.6),
    pores: R.range(0.4, 1.6),
    eyes: R.int(0, 6),
    mouth: R.chance(0.8),
    teeth: R.range(0.2, 1.6),
    slime: R.range(0.3, 1.5),
    grit: R.range(0.5, 1.5),
    wet: R.range(0.2, 1.3),
    palette: R.pick(Object.keys(PALETTES)),
    tentacles: R.int(3, 8),
    tentVariants: R.int(2, 4),
    tentLen: R.int(64, 150),
    tentThick: R.int(6, 14),
    tentTaper: R.range(0.5, 0.9),
    tentHooks: R.range(0.2, 1.6),
    tentRings: R.range(0.3, 1.5)
  };
}
`;

  return wrap('CRAWLER FORGE — generator core (UI stripped)', 'CRAWLERFORGE', core + shim, [
    'P_DEFAULTS', 'CONTROLS', 'PALETTES', 'ORIENTS',
    'forge', 'randomParams', 'drawTentacle', 'states', 'makeRng', 'clamp'
  ]);
}

/* ---------------- scrap forge ---------------- */
function scrapforge() {
  const js = scriptBody(read('tools/scrapforge.html'));
  const uiAt = js.indexOf('   UI\n');
  if (uiAt < 0) throw new Error('scrapforge: UI banner not found');
  let core = js.slice(0, js.lastIndexOf('/* =', uiAt));
  core = core.replace(/^\s*"use strict";\s*/, '');

  const shim = `
/* ---------- game entry point ---------- */
const P_DEFAULTS = Object.assign({}, P);

/* forgeOne()/forgeSet() already swap P around a synchronous build, so
   they are the entry points as-is. This only adds the seeded roll. */
function randomParams(seed) {
  const R = makeRng(seed >>> 0);
  return {
    seed: seed >>> 0,
    palette: R.pick(Object.keys(PALETTES)),
    size: R.int(11, 22),
    grime: R.range(0.5, 1.3),
    grit: R.range(0.6, 1.2),
    wear: R.range(0.35, 1.1),
    markings: R.range(0.2, 1.2),
    lightdir: R.int(0, 359)
  };
}
`;

  return wrap('SCRAP FORGE — generator core (UI stripped)', 'SCRAPFORGE', core + shim, [
    'P_DEFAULTS', 'CONTROLS', 'PALETTES', 'KINDS',
    'forgeOne', 'forgeSet', 'randomParams', 'makeRng', 'clamp'
  ]);
}

const outputs = [
  ['src/gen/greebleworks.js', greebleworks()],
  ['src/gen/mercforge.js', mercforge()],
  ['src/gen/crawlerforge.js', crawlerforge()],
  ['src/gen/scrapforge.js', scrapforge()]
];
for (const [p, src] of outputs) {
  fs.writeFileSync(path.join(ROOT, p), src);
  console.log('wrote ' + p + '  (' + (src.length / 1024).toFixed(1) + ' KB)');
}
