/* ============================================================
   extract.js — slice the generator cores out of the authoring
   tools and emit standalone game modules.

   The tools stay single-file (that's right for a tool). The game
   needs the generators without their UI, and needs both loaded
   side by side — they both declare `clamp` at top level, so each
   core is wrapped in an IIFE and published under one global.

   No build step is required to *play*: src/gen/*.js is committed.
   Re-run this only after editing a tool:

       node tools/extract.js
   ============================================================ */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(ROOT, p), 'utf8');

/* Pull the one <script> body out of a single-file tool. */
function scriptBody(html) {
  const a = html.indexOf('<script>');
  const b = html.lastIndexOf('</script>');
  if (a < 0 || b < 0) throw new Error('no <script> block');
  return html.slice(a + '<script>'.length, b);
}

/* Wrap a core in an IIFE so the two generators cannot collide. */
function wrap(banner, global, core, exports) {
  return `/* ============================================================
   ${banner}

   GENERATED by tools/extract.js — do not edit by hand.
   Edit the tool it came from, then re-run the extractor.
   ============================================================ */
window.${global} = (function () {
"use strict";
${core.trim()}

return { ${exports.join(', ')} };
})();
`;
}

/* ---------------- greebleworks ---------------- */
function greebleworks() {
  const js = scriptBody(read('tools/greebleworks.html'));
  // The UI section is the last banner; everything above it is generator.
  const uiAt = js.indexOf('   UI\n');
  if (uiAt < 0) throw new Error('greebleworks: UI banner not found');
  let core = js.slice(0, js.lastIndexOf('/* =', uiAt));
  core = core.replace(/^\s*"use strict";\s*/, '');

  // The compositor draws 7 layers; the game needs to put entities
  // between the play layer and the foreground. One optional hook.
  const hookAt = core.indexOf('  // lamps and signs');
  if (hookAt < 0) throw new Error('greebleworks: entity hook site not found');
  core = core.slice(0, hookAt)
       + '  if (entityPass) entityPass(ctx, scroll, time);\n\n'
       + core.slice(hookAt);
  core = core.replace(
    'function drawLevelFrame(L,cfg,ctx,scroll,time){',
    'function drawLevelFrame(L,cfg,ctx,scroll,time,entityPass){');

  return wrap('GREEBLEWORKS — generator core (UI stripped)', 'GREEBLEWORKS', core, [
    'LV', 'PALETTES', 'PAL_RGB', 'STYLES', 'SKYMOODS', 'CITY_PRESETS',
    'DECAL_KINDS', 'DECAL_CATS', 'WIRE_STYLE',
    'buildLevel', 'drawLevelFrame', 'bakeFacade', 'bakePlatform', 'bakeRoof',
    'bakeDecal', 'bakeSky', 'makeRng', 'clamp', 'hex2rgb', 'rgbStr', 'mkCanvas'
  ]);
}

/* ---------------- merc forge ---------------- */
function mercforge() {
  const js = scriptBody(read('tools/mercforge.html'));
  const uiAt = js.indexOf('/* ---------- UI ----------');
  if (uiAt < 0) throw new Error('mercforge: UI banner not found');
  const core = js.slice(0, uiAt);

  /* buildSheet() reads the module-global P. The game needs sheets for
     the player and several enemy archetypes, so expose a pure entry
     point that swaps P for the duration of one synchronous build. */
  const shim = `
/* ---------- game entry point ---------- */
const P_DEFAULTS = Object.assign({}, P);

/* Build a sheet from an explicit param set. Synchronous, so swapping
   the module-global P around the call is safe. */
function forge(params) {
  const saved = Object.assign({}, P);
  Object.assign(P, P_DEFAULTS, params || {});
  try { return buildSheet(); }
  finally { Object.assign(P, saved); }
}

/* The tool's randomizer, as a pure function of a seed. */
function randomParams(seed) {
  const R = rng(seed >>> 0);
  const pick = a => a[(R() * a.length) | 0];
  const h = R() * 360, comp = (h + 120 + R() * 140) % 360;
  return {
    seed: seed >>> 0,
    height: 22 + ((R() * 20) | 0),
    headSize: 0.8 + R() * 0.7,
    torsoLen: 0.22 + R() * 0.16,
    legLen: 0.34 + R() * 0.20,
    armLen: 0.30 + R() * 0.20,
    shoulderW: 0.20 + R() * 0.24,
    hipW: 0.14 + R() * 0.14,
    limbThick: 0.045 + R() * 0.05,
    bootSize: R() * 1.6,
    gloveSize: R() * 1.6,
    helmet: pick(['none', 'visor', 'full', 'crest']),
    backpack: pick(['none', 'tank', 'jet', 'pack']),
    gun: pick(['pistol', 'smg', 'rifle', 'cannon', 'beam']),
    gunSize: 0.75 + R() * 0.8,
    twoHanded: R() > 0.3,
    plates: R() > 0.35,
    antenna: R() > 0.65,
    muzzleBrake: R() > 0.4,
    pads: R() * 1.2,
    colSuit: hsl(h, 18 + R() * 30, 38 + R() * 16),
    colSuit2: hsl(h + (R() * 20 - 10), 22 + R() * 24, 16 + R() * 10),
    colAccent: hsl(comp, 55 + R() * 35, 44 + R() * 14),
    colSkin: hsl(22 + R() * 14, 32 + R() * 22, 50 + R() * 24),
    colVisor: hsl((comp + 40) % 360, 70 + R() * 25, 58 + R() * 14),
    colGun: hsl(h + 180, 6 + R() * 10, 40 + R() * 14),
    stride: 0.18 + R() * 0.26,
    lift: 0.06 + R() * 0.14,
    bounce: R() * 0.05,
    runLean: 2 + R() * 16,
    tuck: 0.2 + R() * 0.45
  };
}
`;

  return wrap('MERC FORGE — generator core (UI + demo stripped)', 'MERCFORGE', core + shim, [
    'P_DEFAULTS', 'CONTROLS', 'PRESETS', 'forge', 'randomParams',
    'states', 'gunSpec', 'buildPalette', 'hsl', 'shade', 'hx', 'rh', 'rng', 'clamp'
  ]);
}

const outputs = [
  ['src/gen/greebleworks.js', greebleworks()],
  ['src/gen/mercforge.js', mercforge()]
];
for (const [p, src] of outputs) {
  fs.writeFileSync(path.join(ROOT, p), src);
  console.log('wrote ' + p + '  (' + (src.length / 1024).toFixed(1) + ' KB)');
}
